export const APP_LIST_REQUEST = "APP_LIST_REQUEST";
export const APP_LIST_SUCCESS = "APP_LIST_SUCCESS";
export const APP_LIST_FAIL = "APP_LIST_FAIL";

export const LIST_MENU_REQUEST = "LIST_MENU_REQUEST";
export const LIST_MENU_SUCCESS = "LIST_MENU_SUCCESS";
export const LIST_MENU_FAIL = "LIST_MENU_FAIL";