export const APP_LIST_REQUEST = "APP_LIST_REQUEST";
export const APP_LIST_SUCCESS = "APP_LIST_SUCCESS";
export const APP_LIST_FAIL = "APP_LIST_FAIL";

export const LIST_MENU_REQUEST = "LIST_MENU_REQUEST";
export const LIST_MENU_SUCCESS = "LIST_MENU_SUCCESS";
export const LIST_MENU_FAIL = "LIST_MENU_FAIL";

export const GET_LIST_APP_REQUEST = "GET_LIST_APP_REQUEST";
export const GET_LIST_APP_SUCCESS = "GET_LIST_APP_SUCCESS";
export const GET_LIST_APP_FAIL = "GET_LIST_APP_FAIL";

export const GET_IMG_BANNER_REQUEST = "GET_IMG_BANNER_REQUEST";
export const GET_IMG_BANNER_SUCCESS = "GET_IMG_BANNER_SUCCESS";
export const GET_IMG_BANNER_FAIL = "GET_IMG_BANNER_FAIL";

export const GET_CONTENT_INTRO_REQUEST = "GET_CONTENT_INTRO_REQUEST";
export const GET_CONTENT_INTRO_SUCCESS = "GET_CONTENT_INTRO_SUCCESS";
export const GET_CONTENT_INTRO_FAIL = "GET_CONTENT_INTRO_FAIL";

export const GET_DETAIL_APP_REQUEST = "GET_DETAIL_APP_REQUEST";
export const GET_DETAIL_APP_SUCCESS = "GET_DETAIL_APP_SUCCESS";
export const GET_DETAIL_APP_FAIL = "GET_DETAIL_APP_FAIL";

export const GET_LIST_WEB_REQUEST = "GET_LIST_WEB_REQUEST";
export const GET_LIST_WEB_SUCCESS = "GET_LIST_WEB_SUCCESS";
export const GET_LIST_WEB_FAIL = "GET_LIST_WEB_FAIL";


export const GET_DETAIL_WEB_REQUEST = "GET_DETAIL_WEB_REQUEST";
export const GET_DETAIL_WEB_SUCCESS = "GET_DETAIL_WEB_SUCCESS";
export const GET_DETAIL_WEB_FAIL = "GET_DETAIL_WEB_FAIL";

export const GET_LIST_PRODUCT_REQUEST = "GET_LIST_PRODUCT_REQUEST";
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCT_FAIL = "GET_LIST_PRODUCT_FAIL";